server:
  port: 8080
  servlet:
    context-path: /api
  # 优化Tomcat配置以节省内存
  tomcat:
    threads:
      max: 100          # 减少最大线程数
      min-spare: 10     # 最小空闲线程
    max-connections: 200 # 最大连接数
    accept-count: 50     # 队列长度
    connection-timeout: 20000
  # 启用压缩以减少网络传输
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  datasource:
    url: jdbc:postgresql://yuyingbao-postgres:5432/yuyingbao
    username: yuyingbao
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # 优化连接池配置
    hikari:
      maximum-pool-size: 5      # 减少连接池大小
      minimum-idle: 2           # 最小空闲连接
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false       # 生产环境关闭SQL格式化
        default_schema: app
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 优化Hibernate配置
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: false
    open-in-view: false
    show-sql: false            # 生产环境关闭SQL日志
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: app
    default-schema: app
    create-schemas: true
  # 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

# 日志配置优化
logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    com.yuyingbao: INFO
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: /app/logs/yuyingbao.log
    max-size: 100MB
    max-history: 7

# JVM 内存优化配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: yuyingbao
    expiration-minutes: 43200 # 30 days